#!/bin/sh
#
# Copyright (c) 2015 Spotify AB
#
# This script unregisters menus and icons. It should be run from the top-level
# folder of the uncompressed Spotify distribution.

spotifyPath=$PWD
if [ -e /usr/share/spotify ]; then
  spotifyPath=/usr/share/spotify
fi

# Remove icons from the system icon folders
XDG_ICON_RESOURCE="$(command -v xdg-icon-resource 2> /dev/null)"
if [ ! -x "$XDG_ICON_RESOURCE" ]; then
  echo "Error: Could not find xdg-icon-resource" >&2
  exit 1
fi

for icon in "$spotifyPath"/icons/spotify-linux-*.png; do
  [ -e "$icon" ] || break
  size="${icon##*/spotify-linux-}"
  "$XDG_ICON_RESOURCE" uninstall --noupdate --size "${size%.png}" "$icon" "spotify-client"
done
"$XDG_ICON_RESOURCE" forceupdate

# Remove the entry from the system menu
XDG_DESKTOP_MENU="$(command -v xdg-desktop-menu 2> /dev/null)"
UPDATE_MENUS="$(command -v update-menus 2> /dev/null)"
if [ ! -x "$XDG_DESKTOP_MENU" ]; then
  echo "Error: Could not find xdg-desktop-menu" >&2
  exit 1
fi

"$XDG_DESKTOP_MENU" uninstall --novendor "spotify.desktop"
if [ -x "$UPDATE_MENUS" ]; then
  "$UPDATE_MENUS"
fi
